baseURL               = "/"
languageCode          = "zh-CN"
title                 = "我的网址导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    author        = "okekrr"
    description   = "个人常用网址导航"
    upload        = ""
    about         = ""
    repository    = ""
    enablePreLoad = true
    textPreLoad   = "我的网址导航"
    expandSidebar = false
    logosPath     = "assets/images/logos"
    defaultLogo   = "assets/images/logos/default.webp"
    nightMode     = false
    yiyan         = false
    fancybox      = true

[params.seo]
    baiduhmid       = ''
    baiduSiteVer    = ''
    tj51laid        = ''
    tj51lack        = ''
    GoogleAdsClient = ''

[params.qweather]
    key = ""

[params.images]
    favicon           = "assets/images/bi-favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"
    searchImageD      = "assets/images/bg-dna.jpg"
    logoExpandLight   = "assets/images/bi-expand-dark.png"
    logoExpandDark    = "assets/images/bi-expand-light.png"
    logoCollapseLight = "assets/images/bi.png"
    logoCollapseDark  = "assets/images/bi.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; 2024 - {year} 我的网址导航'
